# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DaleksDeserveVictory's RW Comics
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  DaleksDeserveVictory's RW Comics
  
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

#sidebar
default-image:  rimworld_icon_by_blagoicons.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: KapTaiN_KaVerN
copyright:
   name: DaleksDeserveVictory
   link: 'https://www.twitch.tv/bachheart'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: 

# Comments
disqus-shortname: 

#social
reddit: https://www.reddit.com/user/daleksdeservevictory
twitch: https://www.twitch.tv/bachheart
facebook: 
quora: 
twitter: 
github: 
donation: https://streamtip.com/t/bachheart

#facebook like box
fb-app-id: 
fb-page-url: 
fb-page-title: 

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

# Collections
collections:
  - comics

